name: Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: hl7fhir/ig-publisher-base    # use ig publisher base image https://hub.docker.com/r/hl7fhir/ig-publisher-base
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Update Publisher
      run: ./_updatePublisher.sh -f -y
    - name: Install sushi
      run: npm install -g fsh-sushi
    - name: Run IG Publisher
      run: ./_genonce.sh
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
         name: ig
         path: ./output
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags/v')
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ig
        path: ./output
    - name: Upload archive
      uses: softprops/action-gh-release@v2
      with:
          files: output/package.tgz

